pipeline {
    agent any

    parameters {
        choice(name: 'TERRAFORM_ACTION', choices: ['apply', 'destroy'], description: 'Terraform action to perform')
    }

    stages {

        stage('Build Docker Image') {
            when { expression { params.TERRAFORM_ACTION == 'apply' } }
            steps {
                echo 'Building the Docker image...'
                sh 'docker build -t python-app .'
            }
        }

        stage('Authenticate to GAR') {
            when { expression { params.TERRAFORM_ACTION == 'apply' } }
            steps {
                echo 'Authenticating to Google Artifact Registry...'
                withCredentials([file(credentialsId: 'gar-key', variable: 'GCP_KEY')]) {
                    sh '''
                        gcloud auth activate-service-account --key-file=$GCP_KEY
                        gcloud auth configure-docker us-docker.pkg.dev
                    '''
                }
            }
        }

        stage('Push image to GAR') {
            when { expression { params.TERRAFORM_ACTION == 'apply' } }
            steps {
                echo 'Pushing image to GAR...'
                sh "docker tag python-app:latest us-docker.pkg.dev/hari-chandu-anunay/projectd/img:v1"
                sh "docker push us-docker.pkg.dev/hari-chandu-anunay/projectd/img:v1"
            }
        }

        stage('Terraform Apply') {
            when { expression { params.TERRAFORM_ACTION == 'apply' } }
            steps {
                echo 'Running Terraform apply...'
                withCredentials([file(credentialsId: 'gar-key', variable: 'GCLOUD_KEY')]) {
                    dir('terraform') {
                        sh '''
                            gcloud auth activate-service-account --key-file=$GCLOUD_KEY
                            terraform init
                            terraform apply -auto-approve
                        '''
                    }
                }
            }
        }

        stage('Terraform Destroy') {
            when { expression { params.TERRAFORM_ACTION == 'destroy' } }
            steps {
                echo 'Running Terraform destroy...'
                withCredentials([file(credentialsId: 'gar-key', variable: 'GCLOUD_KEY')]) {
                    dir('terraform') {
                        sh '''
                            gcloud auth activate-service-account --key-file=$GCLOUD_KEY
                            terraform init
                            terraform destroy -auto-approve
                        '''
                    }
                }
            }
        }

        stage('Ansible Deploy') {
            when { expression { params.TERRAFORM_ACTION == 'apply' } }
            steps {
                echo 'Running Ansible playbook...'
                sh '''
                    export ANSIBLE_HOST_KEY_CHECKING=False
                    ansible-playbook -i /root/inv.py ansible/playbook.yml \
                        --ssh-extra-args="-o StrictHostKeyChecking=no"
                '''
            }
        }
    }
}
